-- 🛒 سبد خرید حالا در دیتابیس نگه داشته می‌شود، نه فقط در حافظه گراف.
-- این «منبع واحد حقیقت» است: چه چت‌بات آیتم اضافه کند چه کاربر از UI،
-- هر دو دقیقاً همین جدول را می‌خوانند/می‌نویسند و از طریق Supabase Realtime سینک می‌مانند.

CREATE TABLE IF NOT EXISTS carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'active', -- active | checked_out | abandoned
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    meal_id BIGINT NOT NULL REFERENCES meals(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- وضعیت‌های مجاز سفارش: pending | cooking | completed | cancelled

-- 💬 هر گفتگوی چت‌بات یک ردیف دارد؛ همین‌جا سقف ۱۰ پیام کنترل می‌شود
CREATE TABLE IF NOT EXISTS conversations (
    thread_id TEXT PRIMARY KEY,       -- پیشنهاد: همان user_id به صورت string
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message_count INTEGER NOT NULL DEFAULT 0,
    status TEXT DEFAULT 'open',       -- open | limited
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- برای اینکه فرانت Next.js همان لحظه تغییرات را ببیند (هم اینجا هم در
-- Supabase dashboard → Database → Replication فعال شود):
ALTER PUBLICATION supabase_realtime ADD TABLE cart_items;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE order_items;
